# Raw data collected 2026-08-31 from https://www.techi.com/category (page 1 of each).
# For each of the 6 sections, the 20 most recent articles as listed on the live category page.
# Fields captured directly from the site: section, headline, url, author, date_shown (verbatim).
# Not on the site (computed / judgment calls, documented in method.txt): Headline_word_count, format, names_a_company, contains_a_number.

RAW = [
    # AI
    ("AI", "Google DeepMind's shift to California tests the case for London's AI cluster",
     "https://www.techi.com/deepmind-coding-research-california-london-cluster/", "Zoha Imdad Ali", "Aug 19, 2026"),
    ("AI", "The chip selloff is picking sides, and AMD is on the wrong one",
     "https://www.techi.com/amd-chip-selloff-input-costs-pricing-power/", "Umair Aslam", "Aug 19, 2026"),
    ("AI", "Tesla's robotaxi finally works. Just not on the cars it sold you",
     "https://www.techi.com/tesla-cybercab-hardware-gap-fsd-owners/", "Omer Sheikh", "Aug 19, 2026"),
    ("AI", "Nvidia's H200s are flowing to China again, at 13% of the legal limit",
     "https://www.techi.com/nvidia-h200-china-shipments-below-licence-ceiling/", "Dr Layloma Rashid", "Aug 19, 2026"),
    ("AI", "Samsung lost a third of its foundry share. It raised prices anyway",
     "https://www.techi.com/samsung-foundry-price-hike-losing-share/", "Fatimah Misbah Hussain", "Aug 19, 2026"),
    ("AI", "King's Cross reveals AI's next bottleneck: talent density",
     "https://www.techi.com/kings-cross-ai-talent-cluster-bottleneck/", "Zoha Imdad Ali", "Aug 10, 2026"),
    ("AI", "OpenAI's Astra may be 'Critical.' The proof is still private",
     "https://www.techi.com/openai-astra-critical-cyber-capability-proof/", "Zoha Imdad Ali", "Aug 9, 2026"),
    ("AI", "Firebird's Armenia AI factory is live. The 300 MW promise is not",
     "https://www.techi.com/firebird-armenia-ai-factory-300mw-roadmap/", "Saba Javed", "Aug 9, 2026"),
    ("AI", "Kalanick's Atoms Raised $1.7B to Own the Machines, Not Sell Them",
     "https://www.techi.com/atoms-kalanick-industrial-ai-1-7-billion/", "Fatimah Misbah Hussain", "Jul 25, 2026"),
    ("AI", "Alphabet's Record Profit Hides Its First AI Cash Burn",
     "https://www.techi.com/alphabet-ai-capex-negative-free-cash-flow/", "Fatimah Misbah Hussain", "Jul 25, 2026"),
    ("AI", "Black Forest Labs' FLUX 3 Folds Robotics Into One AI Model",
     "https://www.techi.com/flux-3-multimodal-image-video-audio-action/", "Fatimah Misbah Hussain", "Jul 25, 2026"),
    ("AI", "Inference Chips Are Becoming Loan Collateral in a $400M Bet",
     "https://www.techi.com/inference-chips-loan-collateral-financing/", "Zoha Imdad Ali", "Jul 25, 2026"),
    ("AI", "Fireworks raised $1.5B on a number that reframes open weights: 95%",
     "https://www.techi.com/specialized-inference-economy-fireworks-1-5b/", "Fatimah Misbah Hussain", "Jul 24, 2026"),
    ("AI", "Tesla Crashed 14%. Wall Street's Targets Now Span $130 to $600",
     "https://www.techi.com/tesla-analyst-price-target-cuts-q2-2026-selloff/", "Saba Javed", "Jul 24, 2026"),
    ("AI", "Tesla's Q2 Revenue Set a Record. The AI Bill Took the Profit",
     "https://www.techi.com/tesla-q2-2026-ai-capex-margin-squeeze/", "Saba Javed", "Jul 24, 2026"),
    ("AI", "Kimi K3's open weights arrive July 27. The catch is 1.4TB",
     "https://www.techi.com/kimi-k3-open-weights-inference-economics/", "Fatimah Misbah Hussain", "Jul 24, 2026"),
    ("AI", "Four AI agent platforms launched in a month. None agree what it is",
     "https://www.techi.com/enterprise-ai-agent-platforms-market-structure/", "Zoha Imdad Ali", "Jul 23, 2026"),
    ("AI", "Google shipped three Geminis. The one you can't buy is the story",
     "https://www.techi.com/google-gemini-flash-cyber-restricted-access/", "Fatimah Misbah Hussain", "Jul 23, 2026"),
    ("AI", "Palantir Stock's 6% Drop Is a Moat Test Before August 3 Earnings",
     "https://www.techi.com/palantir-stock-open-source-moat-test/", "Fatimah Misbah Hussain", "Jul 23, 2026"),
    ("AI", "EU AI Act GPAI Enforcement Begins August 2. Who Is Exposed?",
     "https://www.techi.com/eu-ai-act-gpai-enforcement-august-2026/", "Saba Javed", "Jul 23, 2026"),
    # Markets
    ("Markets", "The chip selloff is picking sides, and AMD is on the wrong one",
     "https://www.techi.com/amd-chip-selloff-input-costs-pricing-power/", "Umair Aslam", "Aug 19, 2026"),
    ("Markets", "Tesla's robotaxi finally works. Just not on the cars it sold you",
     "https://www.techi.com/tesla-cybercab-hardware-gap-fsd-owners/", "Omer Sheikh", "Aug 19, 2026"),
    ("Markets", "Samsung lost a third of its foundry share. It raised prices anyway",
     "https://www.techi.com/samsung-foundry-price-hike-losing-share/", "Fatimah Misbah Hussain", "Aug 19, 2026"),
    ("Markets", "Reading the Ether Price After a Brutal First Half of 2026",
     "https://www.techi.com/ether-price-first-half-2026/", "Qaiser Sultan", "Aug 19, 2026"),
    ("Markets", "Intel Just Asked Investors for $15 Billion. The Timing Is the Whole Story",
     "https://www.techi.com/intel-15-billion-stock-offering/", "Omer Sheikh", "Aug 10, 2026"),
    ("Markets", "Tesla Crashed 14%. Wall Street's Targets Now Span $130 to $600",
     "https://www.techi.com/tesla-analyst-price-target-cuts-q2-2026-selloff/", "Saba Javed", "Jul 24, 2026"),
    ("Markets", "Palantir Stock's 6% Drop Is a Moat Test Before August 3 Earnings",
     "https://www.techi.com/palantir-stock-open-source-moat-test/", "Fatimah Misbah Hussain", "Jul 23, 2026"),
    ("Markets", "NVIDIA's 10x Vera Rubin result needs the missing math",
     "https://www.techi.com/nvidia-vera-rubin-coreweave-tokens-per-megawatt/", "Fatima Fakhar", "Jul 21, 2026"),
    ("Markets", "TSM stock faces a 3-4 point margin test as TSMC's first 2nm revenue arrives",
     "https://www.techi.com/tsmc-first-2nm-revenue-margin-test/", "Fatima Fakhar", "Jul 17, 2026"),
    ("Markets", "NRG's PJM capacity haul changes the earnings question",
     "https://www.techi.com/nrg-stock-pjm-capacity-earnings-exposure/", "Muhammad Zeshan Sarwar", "Jul 15, 2026"),
    ("Markets", "AEHR Stock Rally Prices a Backlog Conversion Test",
     "https://www.techi.com/aehr-stock-backlog-conversion-test/", "Hazel Kaya", "Jul 15, 2026"),
    ("Markets", "Eos Energy (EOSE): Q2 Backlog Record Still Has a Margin Hole",
     "https://www.techi.com/eose-q2-preliminary-results-margin-backlog/", "Umair Aslam", "Jul 15, 2026"),
    ("Markets", "CleanSpark's $6.6 Billion Lease Has a $2.1 Billion Question",
     "https://www.techi.com/cleanspark-stock-ai-data-center-lease-capex/", "Hazel Kaya", "Jul 14, 2026"),
    ("Markets", "SLB's AI Data Center Alliance Has One Big Missing Number",
     "https://www.techi.com/slb-liberty-ai-data-center-power-alliance/", "Muhammad Zeshan Sarwar", "Jul 14, 2026"),
    ("Markets", "Who Gets Paid When AI Needs More Memory? A Field Guide to the Toolmakers",
     "https://www.techi.com/ai-memory-equipment/", "Jazib Zaman", "Jul 13, 2026"),
    ("Markets", "ASML Stock Faces an 18B-23B Euro Second-Half Delivery Test",
     "https://www.techi.com/asml-stock-second-half-delivery-test/", "Umair Aslam", "Jul 13, 2026"),
    ("Markets", "Strategy Raises $466.7M From MSTR Stock, Buys No Bitcoin",
     "https://www.techi.com/strategy-mstr-stock-sales-no-bitcoin-july-2026/", "Fatimah Misbah Hussain", "Jul 13, 2026"),
    ("Markets", "SpaceX Stock Hit an All-Time Low a Day After Joining the Nasdaq-100",
     "https://www.techi.com/spacex-stock-fall-spcx-nasdaq-100-lockup/", "Omer Sheikh", "Jul 9, 2026"),
    ("Markets", "Why Lumentum Stock Is Up 115% in 2026, and Jumped 12% on Meta's AI Memo",
     "https://www.techi.com/lumentum-stock-lite-ai-optics-2026/", "Umair Aslam", "Jul 9, 2026"),
    ("Markets", "Why Lam Research Stock Is Up 154% Without Selling a Single Chip",
     "https://www.techi.com/lam-research-stock-lrcx-ai-memory-equipment/", "Jazib Zaman", "Jul 9, 2026"),
    # Crypto
    ("Crypto", "Reading the Ether Price After a Brutal First Half of 2026",
     "https://www.techi.com/ether-price-first-half-2026/", "Qaiser Sultan", "Aug 19, 2026"),
    ("Crypto", "US sanctions two crypto exchanges over Iran-linked money flows",
     "https://www.techi.com/us-sanctions-shelbit-aban-tether-iran-crypto/", "Fatimah Misbah Hussain", "Aug 9, 2026"),
    ("Crypto", "Akash Runs Real AI Compute. AKT Can't Prove It Captures the Value.",
     "https://www.techi.com/akash-akt-ai-compute-value-capture/", "Zoha Imdad Ali", "Jul 24, 2026"),
    ("Crypto", "Grayscale's TAO ETF Can't Stake, Its Own Filing Says So",
     "https://www.techi.com/spot-tao-etf-bittensor-subnet-exposure-gap/", "Zoha Imdad Ali", "Jul 23, 2026"),
    ("Crypto", "Coinbase Let Agents Pay Merchants. The Ledger Says Go Slow",
     "https://www.techi.com/coinbase-x402-agent-payments-merchant-side/", "Zoha Imdad Ali", "Jul 23, 2026"),
    ("Crypto", "Strategy Raises $466.7M From MSTR Stock, Buys No Bitcoin",
     "https://www.techi.com/strategy-mstr-stock-sales-no-bitcoin-july-2026/", "Fatimah Misbah Hussain", "Jul 13, 2026"),
    ("Crypto", "Worldcoin WLD Unlock Cut: What Changes July 24",
     "https://www.techi.com/worldcoin-wld-unlock-rate-43-percent-july-2026/", "Warisha Rashid", "Jul 12, 2026"),
    ("Crypto", "What Actually Makes a Good Crypto Trading Platform in 2026",
     "https://www.techi.com/what-makes-a-good-crypto-trading-platform/", "Qaiser Sultan", "Jul 2, 2026"),
    ("Crypto", "Inside the Roblox Limiteds Economy: How Virtual Collectibles Became Real Money",
     "https://www.techi.com/inside-the-roblox-limiteds-economy/", "Qaiser Sultan", "Jun 30, 2026"),
    ("Crypto", "Why Bitcoin Is Falling So Hard, and Which Altcoins Are Holding Up",
     "https://www.techi.com/why-bitcoin-is-falling-crypto-market-scenarios-june-2026/", "Muhammad Zeshan Sarwar", "Jun 3, 2026"),
    ("Crypto", "Bitcoin's $77K Fear Machine: How Crypto Fear Went Universal",
     "https://www.techi.com/bitcoin-77k-fear-machine/", "Muhammad Zeshan Sarwar", "May 20, 2026"),
    ("Crypto", "FET Crypto Price: The Agent-Payment Gap Behind the ASI Rebound",
     "https://www.techi.com/fet-crypto-price-agent-payment-gap-asi-token/", "Muhammad Zeshan Sarwar", "May 14, 2026"),
    ("Crypto", "Polygon POL Price Analysis: Ex-MATIC Tests Payments Re-Rating",
     "https://www.techi.com/polygon-pol-price-analysis-ex-matic-payments/", "Omer Sheikh", "May 7, 2026"),
    ("Crypto", "Solana Just Became the Wallet for AI Agents",
     "https://www.techi.com/solana-pay-sh-ai-agent-payments/", "Omer Sheikh", "May 6, 2026"),
    ("Crypto", "MicroStrategy Stock (MSTR) Buys 34,164 BTC for $2.54B, Overtakes BlackRock IBIT",
     "https://www.techi.com/mstr-stock-strategy-34164-btc-overtakes-blackrock/", "Omer Sheikh", "Apr 20, 2026"),
    ("Crypto", "XRP Touched $1.50 for the First Time in 2026. The Pullback Isn't the Story.",
     "https://www.techi.com/xrp-price-breakout-analysis/", "Muhammad Zeshan Sarwar", "Apr 18, 2026"),
    ("Crypto", "Bitcoin Moved 7%. MSTR Moved 30%. Inside the Leverage Trade That Works Both Ways",
     "https://www.techi.com/mstr-bitcoin-leverage-trade/", "Omer Sheikh", "Apr 18, 2026"),
    ("Crypto", "Bitcoin Taxes in 2026: IRS Rules, 1099-DA, and Tax Planning Issues",
     "https://www.techi.com/bitcoin-taxes-2026/", "Connor Livingston", "Apr 17, 2026"),
    ("Crypto", "BYDFi Marks 6th Anniversary with Month-Long Celebration, Built for Reliability",
     "https://www.techi.com/bydfi-crypt-exchange/", "Zoha Imdad Ali", "Apr 14, 2026"),
    ("Crypto", "Bitcoin Price Below $71K After Islamabad Collapse: Why Whale Wallets Are Buying What Retail Is Selling",
     "https://www.techi.com/bitcoin-price-xrp-islamabad-collapse/", "Muhammad Zeshan Sarwar", "Apr 13, 2026"),
    # Breakthroughs
    ("Breakthroughs", "AI agents logged 526 chip-material candidates. One recipe passed the screen",
     "https://www.techi.com/ai-chip-materials-synthesis-bottleneck/", "Fatimah Misbah Hussain", "Aug 10, 2026"),
    ("Breakthroughs", "Supernatural's VR fitness reboot aims to restore 3,000 workouts",
     "https://www.techi.com/supernatural-vr-fitness-reboot-3000-workouts/", "Saba Javed", "Aug 9, 2026"),
    ("Breakthroughs", "AI camouflage reportedly passed one camera test. Proof is still thin",
     "https://www.techi.com/ai-camouflage-surveillance-camera-test-proof/", "Zoha Imdad Ali", "Aug 9, 2026"),
    ("Breakthroughs", "Firebird's Armenia AI factory is live. The 300 MW promise is not",
     "https://www.techi.com/firebird-armenia-ai-factory-300mw-roadmap/", "Saba Javed", "Aug 9, 2026"),
    ("Breakthroughs", "Microsoft Is Now Buying Mistral's Compute, Not Selling It",
     "https://www.techi.com/microsoft-mistral-europe-gpu-compute-supply/", "Saba Javed", "Jul 25, 2026"),
    ("Breakthroughs", "Korea's sovereign AI factory is really a $10B financing story",
     "https://www.techi.com/korea-sovereign-ai-factory-naver-nvidia-financing/", "Fatimah Misbah Hussain", "Jul 25, 2026"),
    ("Breakthroughs", "Black Forest Labs' FLUX 3 Folds Robotics Into One AI Model",
     "https://www.techi.com/flux-3-multimodal-image-video-audio-action/", "Fatimah Misbah Hussain", "Jul 25, 2026"),
    ("Breakthroughs", "Google's Ironwood TPU Still Has No Public Price, Three Months After Launch",
     "https://www.techi.com/google-ironwood-tpu-no-public-price/", "Zoha Imdad Ali", "Jul 24, 2026"),
    ("Breakthroughs", "Z.ai built a gigawatt of AI compute with no Nvidia inside",
     "https://www.techi.com/z-ai-gigawatt-chinese-chips-data-center/", "Saba Javed", "Jul 24, 2026"),
    ("Breakthroughs", "AMD and Cerebras Split AI Inference in Two, Read the Footnote",
     "https://www.techi.com/amd-cerebras-disaggregated-inference-5x-claim/", "Saba Javed", "Jul 23, 2026"),
    ("Breakthroughs", "Amazon's $20B chip pace turns AI capacity into a supply contract",
     "https://www.techi.com/amazon-trainium-20-billion-supply-contract/", "Saba Javed", "Jul 23, 2026"),
    ("Breakthroughs", "llama.cpp b10075 Packs Four Local AI Runtime Upgrades",
     "https://www.techi.com/llama-cpp-b10075-local-ai-agent-runtime/", "Zoha Imdad Ali", "Jul 21, 2026"),
    ("Breakthroughs", "Fenghe Is Open Source. Its Forecasting Proof Is Not.",
     "https://www.techi.com/fenghe-open-source-weather-ai-evidence-gap/", "Jazib Zaman", "Jul 18, 2026"),
    ("Breakthroughs", "CrewAI 1.15.3 Puts Control Hooks Inside AI Agent Runs",
     "https://www.techi.com/crewai-1-15-3-execution-hooks-agent-control/", "Jazib Zaman", "Jul 17, 2026"),
    ("Breakthroughs", "JAX 0.11.0 Makes AI Training Memory Policy Programmable",
     "https://www.techi.com/jax-0-11-0-remat-checkpoint-policies/", "Jazib Zaman", "Jul 17, 2026"),
    ("Breakthroughs", "ASML's High-NA Milestone Is an AI-Chip Bridge",
     "https://www.techi.com/asml-high-na-euv-intel-18a-ai-chip-readiness/", "Umair Aslam", "Jul 15, 2026"),
    ("Breakthroughs", "Samsung's 20x Flex Titanium Claim Is Not a Durability Test",
     "https://www.techi.com/samsung-flex-titanium-foldable-display-durability/", "Jazib Zaman", "Jul 15, 2026"),
    ("Breakthroughs", "GitHub's Dependabot Cooldown Has an Install-Layer Gap",
     "https://www.techi.com/github-dependabot-cooldown-install-layer-gap/", "Jazib Zaman", "Jul 14, 2026"),
    ("Breakthroughs", "Inside the Roblox Limiteds Economy: How Virtual Collectibles Became Real Money",
     "https://www.techi.com/inside-the-roblox-limiteds-economy/", "Qaiser Sultan", "Jun 30, 2026"),
    ("Breakthroughs", "Rocket Lab's $8 Billion Iridium Deal Is a Bet on the Whole Space Stack",
     "https://www.techi.com/rocket-lab-iridium-8-billion-acquisition/", "Umair Aslam", "Jun 30, 2026"),
    # Policy
    ("Policy", "The Meta trial's real risk isn't the $1.4 trillion. It's the judge",
     "https://www.techi.com/meta-29-state-trial-advisory-jury-remedy-risk/", "Saba Javed", "Aug 19, 2026"),
    ("Policy", "Nvidia's H200s are flowing to China again, at 13% of the legal limit",
     "https://www.techi.com/nvidia-h200-china-shipments-below-licence-ceiling/", "Dr Layloma Rashid", "Aug 19, 2026"),
    ("Policy", "Anthropic's Model 2 Is Stronger. That Isn't Why the Risk Label Changed",
     "https://www.techi.com/anthropic-model-2-risk-report-misalignment-estimate/", "Qaiser Sultan", "Aug 14, 2026"),
    ("Policy", "X will pay for original posts. Only Premium views count",
     "https://www.techi.com/x-original-content-rewards-premium-impressions/", "Fatimah Misbah Hussain", "Aug 9, 2026"),
    ("Policy", "OpenAI's Astra may be 'Critical.' The proof is still private",
     "https://www.techi.com/openai-astra-critical-cyber-capability-proof/", "Zoha Imdad Ali", "Aug 9, 2026"),
    ("Policy", "The FTC Says Complying With State AI Laws Can Still Be Illegal",
     "https://www.techi.com/ftc-ai-accuracy-deception-state-law/", "Saba Javed", "Jul 25, 2026"),
    ("Policy", "Three firms hold 84% of AI agents. France just drew a line.",
     "https://www.techi.com/ai-agent-market-concentration-antitrust/", "Saba Javed", "Jul 24, 2026"),
    ("Policy", "The AI omnibus moved every deadline except the ones due next month",
     "https://www.techi.com/eu-ai-act-omnibus-deadline-map/", "Saba Javed", "Jul 23, 2026"),
    ("Policy", "EU AI Act GPAI Enforcement Begins August 2. Who Is Exposed?",
     "https://www.techi.com/eu-ai-act-gpai-enforcement-august-2026/", "Saba Javed", "Jul 23, 2026"),
    ("Policy", "EU AI Act Makes AI Agents Say Who Sent Them",
     "https://www.techi.com/eu-ai-act-ai-agents-disclose-who-sent-them/", "Nouman S. Ghumman", "Jul 21, 2026"),
    ("Policy", "EU Opens 11 Android Features to Rival AI Assistants",
     "https://www.techi.com/eu-google-ai-interoperability-android-dma/", "Nouman S. Ghumman", "Jul 17, 2026"),
    ("Policy", "OpenAI's New Teen Alert Comes After a ChatGPT Account Ban",
     "https://www.techi.com/openai-chatgpt-teen-alerts-violent-activity-bans/", "Dr Layloma Rashid", "Jul 16, 2026"),
    ("Policy", "Britain's AI Data Review Opens a Public-Data Pricing Fight",
     "https://www.techi.com/uk-ai-data-regulation-public-data-pricing/", "Nouman S. Ghumman", "Jul 15, 2026"),
    ("Policy", "UK AI Battle Lab Turns Army Training Into a Data Loop",
     "https://www.techi.com/uk-ai-battle-lab-army-training-data-loop/", "Nouman S. Ghumman", "Jul 12, 2026"),
    ("Policy", "Washington Thinks China Has ASML's Best Machine. ASML Says It's Impossible.",
     "https://www.techi.com/asml-china-euv-export-scrutiny-stock/", "Umair Aslam", "Jun 19, 2026"),
    ("Policy", "AI progress so far, and the next 10 years that matter",
     "https://www.techi.com/ai-progress-next-10-years-forecast/", "Nouman S. Ghumman", "May 28, 2026"),
    ("Policy", "Starlink's Real Moat Is the Country Map, Not Space",
     "https://www.techi.com/starlink-availability-country-map/", "Omer Sheikh", "May 18, 2026"),
    ("Policy", "Tesla Semi momentum: fleet orders test a $1 trillion market",
     "https://www.techi.com/tesla-semi-fleet-orders-trucking-margin-stock/", "Omer Sheikh", "May 16, 2026"),
    ("Policy", "Tesla Stock: The China Meeting Premium Is Back",
     "https://www.techi.com/tesla-stock-trump-china-meeting-premium/", "Fatimah Misbah Hussain", "May 14, 2026"),
    ("Policy", "AI's Real Job Shock Is the Missing Rung",
     "https://www.techi.com/ai-jobs-career-ladder-tech-intelligence/", "Jazib Zaman", "May 9, 2026"),
    # Guides
    ("Guides", "Claude Code will default to auto mode despite an 11% test miss rate",
     "https://www.techi.com/claude-code-auto-mode-default-11-percent-miss-rate/", "Saba Javed", "Aug 9, 2026"),
    ("Guides", "What Meta AI's Email and Calendar Agent Actually Changes",
     "https://www.techi.com/meta-ai-email-calendar-agent-permissions/", "Zoha Imdad Ali", "Jul 27, 2026"),
    ("Guides", "DeepSeek's legacy model names retire today, and the easy fix has a catch",
     "https://www.techi.com/deepseek-chat-reasoner-retirement-v4-migration/", "Zoha Imdad Ali", "Jul 24, 2026"),
    ("Guides", "OpenAI Presence sells trusted agents. Here is the buyer's checklist",
     "https://www.techi.com/openai-presence-enterprise-agents-buyer-checklist/", "Zoha Imdad Ali", "Jul 23, 2026"),
    ("Guides", "Harness Agent DLC Puts AI Releases Under One Change Record",
     "https://www.techi.com/harness-agent-dlc-ai-release-governance/", "Ayesha Riaz", "Jul 21, 2026"),
    ("Guides", "Claude Code 2.1.216 Tests Whether Agent Permissions Survive the Handoff",
     "https://www.techi.com/claude-code-update-agent-permissions-worktree-isolation/", "Zoha Imdad Ali", "Jul 20, 2026"),
    ("Guides", "Cline CLI 3.0.45 cuts install footprint by unbundling AI providers",
     "https://www.techi.com/cline-cli-3-0-45-ai-agent-install-size/", "Ayesha Riaz", "Jul 19, 2026"),
    ("Guides", "Xinference 3.0's Biggest AI Upgrade Is a 401 Error",
     "https://www.techi.com/xinference-3-default-auth-air-gapped-ai-serving/", "Zoha Imdad Ali", "Jul 19, 2026"),
    ("Guides", "Grok on Amazon Bedrock Has an Enterprise Portability Catch",
     "https://www.techi.com/grok-bedrock-portability-retention-regions/", "Omer Sheikh", "Jul 16, 2026"),
    ("Guides", "llama.cpp's 4.26x Intel Gain Has a Narrow Catch",
     "https://www.techi.com/llama-cpp-intel-battlemage-flash-attention-benchmark/", "Zoha Imdad Ali", "Jul 15, 2026"),
    ("Guides", "Qwen3.5 on Ironwood: What Google's 4.7x Gain Proves",
     "https://www.techi.com/google-qwen3-5-ironwood-software-codesign-speedup/", "Zoha Imdad Ali", "Jul 15, 2026"),
    ("Guides", "NSA Router Security Checklist for Enterprise Networks",
     "https://www.techi.com/nsa-router-security-checklist-enterprise-networks/", "Zoha Imdad Ali", "Jul 13, 2026"),
    ("Guides", "What Is an M&A Advisory?",
     "https://www.techi.com/what-is-an-ma-advisory/", "Umair Aslam", "Jun 30, 2026"),
    ("Guides", "Best AI Security Platforms for Enterprise in 2026",
     "https://www.techi.com/best-ai-security-platforms-enterprise/", "Umair Aslam", "Jun 30, 2026"),
    ("Guides", "Grok Build turns xAI into an AI coding-agent contender",
     "https://www.techi.com/grok-build-xai-coding-agent/", "Jazib Zaman", "May 26, 2026"),
    ("Guides", "2026 AI Trading Bot Guide: 8 Free Stock Trading Tools Retail Traders Are Using",
     "https://www.techi.com/2026-ai-trading-bot-guide-free-stock-trading-tools/", "Guest Author", "May 18, 2026"),
    ("Guides", "AI's Real Job Shock Is the Missing Rung",
     "https://www.techi.com/ai-jobs-career-ladder-tech-intelligence/", "Jazib Zaman", "May 9, 2026"),
    ("Guides", "29 Best Cybersecurity Books Worth Reading in 2026",
     "https://www.techi.com/best-cybersecurity-books/", "Warisha Rashid", "Mar 31, 2026"),
    ("Guides", "The Hidden SEO Challenges of Crypto Platforms And How to Overcome Them",
     "https://www.techi.com/crypto-platform-seo-challenges-and-solutions/", "Guest Author", "Mar 12, 2026"),
    ("Guides", "Top 5 Network Security Companies Every Business Should Know",
     "https://www.techi.com/top-network-security-companies/", "Muhammad Saqib", "Mar 11, 2026"),
]
assert len(RAW) == 120, f"Expected 120 rows, got {len(RAW)}"